name: Backup Odoo on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Execute Backup Script on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "🔗 Terhubung ke server. Memulai script backup..."
            bash /home/azureuser/scripts/backup_odoo.sh
            
      - name: Backup Completed
        if: success()
        run: echo "✅ Backup Odoo berhasil dieksekusi setelah push!"
